name: clean_interface
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Additional features 
  path_provider: ^2.0.1
  share_plus: ^7.2.2
  flex_color_scheme: ^7.3.1
  # State management
  flutter_riverpod: ^2.2.0
  # Functional programming
  equatable: ^2.0.5
  dartz: ^0.10.1
  # Remote API
  http: ^1.2.1
  # Local cache
  hive_flutter: ^1.1.0
  envied: ^0.5.3
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0

flutter:
  generate: true